### ISSUE TITLE
Gemfile issues

### ISSUE THREAD

**Issue by tyyko** [cf-platform-eng/cf-containers-broker#14]
Hello, trying to building the image, I got this:

(just edited Gemfile to use https protocol for github because I am behind a proxy)

```
Fetching https://github.com/cloudfoundry/omniauth-uaa-oauth2.git
Fetching https://github.com/cloudfoundry/cf-registrar.git
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "nats":
  In snapshot (Gemfile.lock):
    nats (= 0.5.0.beta.14)

  In Gemfile:
    cf-registrar (>= 0) ruby depends on
      cf-message-bus (~> 0.3.0) ruby depends on
        nats (< 0.6, >= 0.5.0.beta.16) ruby

    nats (>= 0) ruby

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

```

I simply edited the Dockerfile with the ```bundle update``` command on RUN

Or you can edit the Gemfile.lock at line 104 to

``` nats (0.5.0.beta.16) ``` to get it working

**Comment by frodenas** [comment]
@tyyko I updated the Gemfile (and Gemfile.lock) files to use https instead of git and didn't ran into this problem. The change is on master now (https://github.com/cf-platform-eng/cf-containers-broker/commit/7c07eb7f8a8a7b22c7a32075b2fecde4d19bc7b7) and the automatic [Docker Hub build](https://registry.hub.docker.com/u/frodenas/cf-containers-broker/builds_history/46160/) also ran successfully.

**Comment by frodenas** [comment]
I'm going to close this issue, but feel free to reopen if you cannot make it working.
