### ISSUE TITLE
bosh deploy - busy disk on unmount

### ISSUE THREAD

**Issue by poblin-orange** [cf-platform-eng/cf-containers-broker#16]
Hello,
we finally had the time to check the cf-containers-brokers. Really nice extension to the current bosh capabilities.

We experience issues while testing the broker container, and trying a bosh update after a successfull first deployment.
It seems that the persistent disk is busy when bosh tries to unmount the disk from the original VM.
see logs below.

We use latest version:
- bosh-vcloud-esxi-ubuntu-trusty-go_agent 2922, with vcloud CPI
- bosh 148
- cf-containers-broker v11

Any idea why the persistent disk cant be unmounted ? 
Best regards
Pierre

  Started updating job broker > broker/0. Failed: Action Failed get_task: Task c3dc2d78-19c4-4bfe-4f91-10b9f1246e21 result: Unmounting persistent disk: Running command: 'umount /dev/sdc1', stdout: '', stderr: 'umount: /var/vcap/store: device is busy.
        (In some cases useful info about processes that use
         the device is found by lsof(8) or fuser(1))
': exit status 1 (00:10:03)

Error 450001: Action Failed get_task: Task c3dc2d78-19c4-4bfe-4f91-10b9f1246e21 result: Unmounting persistent disk: Running command: 'umount /dev/sdc1', stdout: '', stderr: 'umount: /var/vcap/store: device is busy.
        (In some cases useful info about processes that use
         the device is found by lsof(8) or fuser(1))
': exit status 1

Task 1099 error

**Comment by frodenas** [comment]
This has been reported previously (https://github.com/cf-platform-eng/docker-boshrelease/issues/13) and I'm still trying to figure out why this is happening.

My guess is that the service broker [kills the container](https://github.com/cf-platform-eng/cf-containers-broker/blob/master/app/models/docker_manager.rb#L82) instead of stopping it and giving it a grace period. I've observed something similar when using just the docker bosh release, as it's also [killing the containers](https://github.com/cf-platform-eng/docker-boshrelease/blob/master/jobs/cf-containers-broker/templates/bin/cf-containers-broker_ctl#L55).

What I've observed is that the container process is NOT able to stop correctly when Docker tris to kill it. Docker believes that the container has been destroyed, but the reality is that if you do a `ps` you'll see the process there, so if the process has a volume mounted, you won't be able to unmount the persistent disk. 

Some time ago I added a [hack to unmount all the container volumes](https://github.com/cf-platform-eng/docker-boshrelease/blob/master/jobs/docker/templates/bin/docker_ctl#L84), but seem it's not working properly.

So something I'd like to try is to replace the killing process by some kind of drain process and let the process die gracefully.

**Comment by vlerenc** [comment]
Hello,

@holgerkoser and I ran into the same issue and found a solution. Basically, what we did was to stop the containers in the monit stop routine implemented in https://github.com/cf-platform-eng/docker-boshrelease/blob/master/jobs/docker/templates/bin/docker_ctl. This helps for the plain broker+docker deployment and also for the more complex broker+swarm+dockers deployments (and is an autonomous solution/not issued by swarm, which is good/safe). Since the containers are started with restart=always, the containers will be restarted when the daemon is restarted.

Indeed, the manual unmount in the same file wasn't working for us either. It looks as if those lines could be deleted/replaced with (sorry for the pseudo code for now and no pull request instead):
```
get list of running docker containers
for each docker container do
  stop docker container
done
continue with kill of docker daemon
```

Interestingly, also the stop will terminate the container hard after (default) 10 seconds. However, after we implemented the the above loop before the docker daemon gets killed we had no issue anymore (may be by chance, not sure we already understand the mechanics well enough).

Best regards, Vedran

P.S.: That was the reason why we opened btw. https://github.com/cf-platform-eng/docker-boshrelease/issues/23 as we wanted to call the docker CLI to loop and stop the containers.

**Comment by frodenas** [comment]
@vlerenc PR or it doesn't exists! :)

**Comment by vlerenc** [comment]
I know, I know, it's not my call - waiting for approval on our side. Should be coming soon, but it really isn't much code either and as I said, not sure if it will always work. However, we haven't had any issues since we changed this. At least docker now kills its containers and not monit is killing docker. ;-)

**Comment by vlerenc** [comment]
@frodenas How about https://github.com/cf-platform-eng/docker-boshrelease/pull/24?

**Comment by frodenas** [comment]
Thanks @vlerenc!

@poblin-orange I'm going to cut a new release this weekend, until then I'll keep this issue open.

**Comment by poblin-orange** [comment]
Thank you guys! Eager to test that new release :-)

**Comment by frodenas** [comment]
New [v13 release](http://bosh.io/releases/github.com/cf-platform-eng/docker-boshrelease?version=13) has the fix.

Reopen if still fails to unmount the pd.
