### ISSUE TITLE
Don't set env SETTINGS_PATH in Dockerfile

### ISSUE THREAD

**Issue by charyorde** [cf-platform-eng/cf-containers-broker#19]
Makes it difficult to override because all files in host have been copied over to `/app`. I think this is also why a local build fails

Alternatively, remove this `ADD ./config/settings.yml /config/settings.yml` . Seems it overrides the custom env var.

**Comment by frodenas** [comment]
It's a best practice to put all files that can be overriden on a separate directory, this is why the config files are set on a different path (`/config`).

In order to override them, you just need to use the `--volume` directory when starting the container. This example will map the `/config` directory inside the container to your host `/tmp/cf-containers-broker/config` directory.

```
--volume /tmp/cf-containers-broker/config:/config
```


The SETTINGS_PATH is set by default to the `/config` directory. You don't need to set it unless you want to use a different directory. In this example we will mount a different config directory and we will set the env var to point to that directory:

```
--volume /tmp/cf-containers-broker/config:/my-custom-config
-e SETTINGS_PATH=/my-custom-config
```
Hope this helps.
